Traceback (most recent call last):
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
n = 1
grp_1_plots = create_results_plots(group_results[n]['results'], group_results[n]['results'])
layout = gridplot(grp_1_plots, ncols=2, width=350, height=300)
show(layout)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn [12], line 2[0m
[1;32m      1[0m n [38;5;241m=[39m [38;5;241m1[39m
[0;32m----> 2[0m grp_1_plots [38;5;241m=[39m [43mcreate_results_plots[49m[43m([49m[43mgroup_results[49m[43m[[49m[43mn[49m[43m][49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mresults[39;49m[38;5;124;43m'[39;49m[43m][49m[43m,[49m[43m [49m[43mgroup_results[49m[43m[[49m[43mn[49m[43m][49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mresults[39;49m[38;5;124;43m'[39;49m[43m][49m[43m)[49m
[1;32m      3[0m layout [38;5;241m=[39m gridplot(grp_1_plots, ncols[38;5;241m=[39m[38;5;241m2[39m, width[38;5;241m=[39m[38;5;241m350[39m, height[38;5;241m=[39m[38;5;241m300[39m)
[1;32m      4[0m show(layout)

Cell [0;32mIn [9], line 10[0m, in [0;36mcreate_results_plots[0;34m(all_test_results, attribute_sets)[0m
[1;32m      7[0m y1 [38;5;241m=[39m [all_test_results[e][[38;5;124m'[39m[38;5;124mtest_rmse[39m[38;5;124m'[39m] [38;5;28;01mfor[39;00m e [38;5;129;01min[39;00m attribute_sets]
[1;32m      8[0m y2 [38;5;241m=[39m [all_test_results[e][[38;5;124m'[39m[38;5;124mtest_mae[39m[38;5;124m'[39m] [38;5;28;01mfor[39;00m e [38;5;129;01min[39;00m attribute_sets]
[0;32m---> 10[0m source [38;5;241m=[39m [43mColumnDataSource[49m[43m([49m[43m{[49m[38;5;124;43m'[39;49m[38;5;124;43mx[39;49m[38;5;124;43m'[39;49m[43m:[49m[43m [49m[43mattribute_sets[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43my1[39;49m[38;5;124;43m'[39;49m[43m:[49m[43m [49m[43my1[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43my2[39;49m[38;5;124;43m'[39;49m[43m:[49m[43m [49m[43my2[49m[43m}[49m[43m)[49m
[1;32m     12[0m title [38;5;241m=[39m [38;5;124mf[39m[38;5;124m'[39m[38;5;124mRunoff Predictability[39m[38;5;124m'[39m
[1;32m     14[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(plots) [38;5;241m==[39m [38;5;241m0[39m:

File [0;32m~/Documents/code/data_analysis/lib/python3.10/site-packages/bokeh/models/sources.py:243[0m, in [0;36mColumnDataSource.__init__[0;34m(self, *args, **kwargs)[0m
[1;32m    241[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mexpected a dict or pandas.DataFrame, got [39m[38;5;132;01m{[39;00mraw_data[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    242[0m [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m([38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m--> 243[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdata[49m[38;5;241;43m.[39;49m[43mupdate[49m[43m([49m[43mraw_data[49m[43m)[49m

File [0;32m~/Documents/code/data_analysis/lib/python3.10/site-packages/bokeh/core/property/wrappers.py:433[0m, in [0;36mPropertyValueColumnData.update[0;34m(self, *args, **kwargs)[0m
[1;32m    431[0m [38;5;28;01mfor[39;00m (owner, descriptor) [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39m_owners:
[1;32m    432[0m     hint [38;5;241m=[39m ColumnDataChangedEvent(owner[38;5;241m.[39mdocument, owner, [38;5;124m"[39m[38;5;124mdata[39m[38;5;124m"[39m, cols[38;5;241m=[39m[38;5;28mlist[39m(cols))
[0;32m--> 433[0m     [43mdescriptor[49m[38;5;241;43m.[39;49m[43m_notify_mutated[49m[43m([49m[43mowner[49m[43m,[49m[43m [49m[43mold[49m[43m,[49m[43m [49m[43mhint[49m[38;5;241;43m=[39;49m[43mhint[49m[43m)[49m
[1;32m    435[0m [38;5;28;01mreturn[39;00m result

File [0;32m~/Documents/code/data_analysis/lib/python3.10/site-packages/bokeh/core/property/descriptors.py:655[0m, in [0;36mPropertyDescriptor._notify_mutated[0;34m(self, obj, old, hint)[0m
[1;32m    651[0m value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m[38;5;21m__get__[39m(obj, obj[38;5;241m.[39m[38;5;18m__class__[39m)
[1;32m    653[0m [38;5;66;03m# re-validate because the contents of 'old' have changed,[39;00m
[1;32m    654[0m [38;5;66;03m# in some cases this could give us a new object for the value[39;00m
[0;32m--> 655[0m value [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mproperty[49m[38;5;241;43m.[39;49m[43mprepare_value[49m[43m([49m[43mobj[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mname[49m[43m,[49m[43m [49m[43mvalue[49m[43m,[49m[43m [49m[43mhint[49m[38;5;241;43m=[39;49m[43mhint[49m[43m)[49m
[1;32m    657[0m [38;5;28mself[39m[38;5;241m.[39m_set(obj, old, value, hint[38;5;241m=[39mhint)

File [0;32m~/Documents/code/data_analysis/lib/python3.10/site-packages/bokeh/core/property/bases.py:363[0m, in [0;36mProperty.prepare_value[0;34m(self, owner, name, value, hint)[0m
[1;32m    361[0m [38;5;28;01melse[39;00m:
[1;32m    362[0m     obj_repr [38;5;241m=[39m owner [38;5;28;01mif[39;00m [38;5;28misinstance[39m(owner, HasProps) [38;5;28;01melse[39;00m owner[38;5;241m.[39m[38;5;18m__name__[39m
[0;32m--> 363[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mfailed to validate [39m[38;5;132;01m{[39;00mobj_repr[38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m: [39m[38;5;132;01m{[39;00merror[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    365[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(owner, HasProps):
[1;32m    366[0m     obj [38;5;241m=[39m owner

[0;31mValueError[0m: failed to validate ColumnDataSource(id='p1001', ...).data: expected a dict of type ColumnData(String, Seq(Any)), got a dict with invalid values for keys: x
ValueError: failed to validate ColumnDataSource(id='p1001', ...).data: expected a dict of type ColumnData(String, Seq(Any)), got a dict with invalid values for keys: x

