Traceback (most recent call last):
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# open an example pairwise results file
pairs_results_folder = os.path.join(
    BASE_DIR, "data", "divergence_test_results",
)
pairs_files = os.listdir(pairs_results_folder)
test_df = pd.read_csv(os.path.join(pairs_results_folder, pairs_files[0]), nrows=1000)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[3], line 5[0m
[1;32m      1[0m [38;5;66;03m# open an example pairwise results file[39;00m
[1;32m      2[0m pairs_results_folder [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(
[1;32m      3[0m     BASE_DIR, [38;5;124m"[39m[38;5;124mdata[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mdivergence_test_results[39m[38;5;124m"[39m,
[1;32m      4[0m )
[0;32m----> 5[0m pairs_files [38;5;241m=[39m [43mos[49m[38;5;241;43m.[39;49m[43mlistdir[49m[43m([49m[43mpairs_results_folder[49m[43m)[49m
[1;32m      6[0m test_df [38;5;241m=[39m pd[38;5;241m.[39mread_csv(os[38;5;241m.[39mpath[38;5;241m.[39mjoin(pairs_results_folder, pairs_files[[38;5;241m0[39m]), nrows[38;5;241m=[39m[38;5;241m1000[39m)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/danbot2/code_5820/24/divergence_measures/docs/notebooks/data/divergence_test_results'

