Traceback (most recent call last):
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/danbot2/code_5820/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# load the catchment characteristics
fname = 'BCUB_watershed_attributes_updated.csv'
attr_df = pd.read_csv(os.path.join('data', fname))
attr_df.columns = [c.lower() for c in df.columns]
station_ids = attr_df['official_id'].values
print(f'There are {len(station_ids)} monitored basins in the attribute set.')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 4[0m
[1;32m      2[0m fname [38;5;241m=[39m [38;5;124m'[39m[38;5;124mBCUB_watershed_attributes_updated.csv[39m[38;5;124m'[39m
[1;32m      3[0m attr_df [38;5;241m=[39m pd[38;5;241m.[39mread_csv(os[38;5;241m.[39mpath[38;5;241m.[39mjoin([38;5;124m'[39m[38;5;124mdata[39m[38;5;124m'[39m, fname))
[0;32m----> 4[0m attr_df[38;5;241m.[39mcolumns [38;5;241m=[39m [c[38;5;241m.[39mlower() [38;5;28;01mfor[39;00m c [38;5;129;01min[39;00m [43mdf[49m[38;5;241m.[39mcolumns]
[1;32m      5[0m station_ids [38;5;241m=[39m attr_df[[38;5;124m'[39m[38;5;124mofficial_id[39m[38;5;124m'[39m][38;5;241m.[39mvalues
[1;32m      6[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mThere are [39m[38;5;132;01m{[39;00m[38;5;28mlen[39m(station_ids)[38;5;132;01m}[39;00m[38;5;124m monitored basins in the attribute set.[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'df' is not defined

